<testsuite name="Mocha Tests" tests="18" failures="4" errors="4" skipped="0" timestamp="Tue, 17 Jul 2018 05:01:20 GMT" time="1.19">
<testcase classname="POST /add" name="shoud response text with responceCode200." time="0"><failure>expected 404 to be 200
AssertionError: expected 404 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&#x3C;anonymous&#x3E; (test/routes/add.test.js:14:27)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.assert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1660:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)</failure></testcase>
<testcase classname="GET /addend" name="shoud response text with responceCode200." time="0"><failure>expected 404 to be 200
AssertionError: expected 404 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&#x3C;anonymous&#x3E; (test/routes/addend.test.js:14:27)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.assert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1660:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)</failure></testcase>
<testcase classname="GET /adderr" name="shoud response text with responceCode200." time="0.074"/>
<testcase classname="POST /addreq" name="shoud response text with responceCode200." time="0.033"/>
<testcase classname="POST /del" name="shoud response text with responceCode200." time="0"><failure>expected 404 to be 200
AssertionError: expected 404 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&#x3C;anonymous&#x3E; (test/routes/del.test.js:14:27)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.assert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1660:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)</failure></testcase>
<testcase classname="GET /delend" name="shoud response text with responceCode200." time="0.07"/>
<testcase classname="GET /delerr1" name="shoud response text with responceCode200." time="0.067"/>
<testcase classname="GET /delerr2" name="shoud response text with responceCode200." time="0.041"/>
<testcase classname="GET /delerr3" name="shoud response text with responceCode200." time="0.052"/>
<testcase classname="POST /delreq" name="shoud response text with responceCode200." time="0.054"/>
<testcase classname="GET /" name="shoud response text with responceCode200." time="0.02"/>
<testcase classname="POST /login" name="shoud response text with responceCode200." time="0"><failure>expected 404 to be 200
AssertionError: expected 404 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&#x3C;anonymous&#x3E; (test/routes/login.test.js:14:27)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.assert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1660:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)</failure></testcase>
<testcase classname="POST /logout" name="shoud response text with responceCode200." time="0.029"/>
<testcase classname="GET /ref" name="shoud response text with responceCode200." time="0.022"/>
<testcase classname="GET /refend" name="shoud response text with responceCode200." time="0.025"/>
<testcase classname="GET /referr1" name="shoud response text with responceCode200." time="0.018"/>
<testcase classname="GET /referr2" name="shoud response text with responceCode200." time="0.031"/>
<testcase classname="GET /refreq" name="shoud response text with responceCode200." time="0.031"/>
</testsuite>
